# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
  app.books_uploader:
    class: AppBundle\FileUploader
    arguments: ['%absolute_dir%', '%books_upload_dir%']
  app.covers_uploader:
    class: AppBundle\FileUploader
    arguments: ['%absolute_dir%', '%covers_upload_dir%']
  app.doctrine_brochure_listener:
    class: AppBundle\EventListener\BookFileUploadListener
    arguments: ['@app.covers_uploader', '@app.books_uploader']
    tags:
        - { name: doctrine.event_listener, event: prePersist }
        - { name: doctrine.event_listener, event: preUpdate }
  cache:
    class: Doctrine\Common\Cache\FilesystemCache
    arguments: ['%cache_dir%']